kind: pipeline
name: default

steps:
  #passo desnecessario, fiz so pra ver funcionar // podia usar a plugins/docker que faz todos os passos
- name: build
  image: docker
  environment:
    - DOCKER_HOST=unix:///drone/docker.sock
  commands:
  - docker build -t tracer .
  - docker tag tracer victorhbfernandes/tracer:${DRONE_COMMIT}

- name: push
  image: docker
  environment:
    - DOCKER_HOST=unix:///drone/docker.sock
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker push victorhbfernandes/tracer:${DRONE_COMMIT}
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
