kind: pipeline
name: default
type: kubernetes

steps:
  #passo desnecessario, fiz so pra ver funcionar // podia usar a plugins/docker que faz todos os passos
- name: build
  image: plugins/docker
  settings:
    debug: true
  commands:
  - docker build -t tracer .
  - docker tag tracer victorhbfernandes/tracer:${DRONE_COMMIT}

- name: push
  image: plugins/docker
  settings:
    debug: true
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker push victorhbfernandes/tracer:${DRONE_COMMIT}
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
